services:
  - type: web
    name: car-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-railway-db-name
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_EMAIL_APP_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false